### ISSUE TITLE
可实现本地运算

### ISSUE THREAD

**Issue by SerinaNya** [shniubobo/bilibili_bv2av#1]
知乎一巨佬已实现：
https://www.zhihu.com/question/381784377/answer/1099438784

**记得注明来源哦~**

**Comment by shniubobo** [comment]
这个巨佬的答案的确值得学习
另外来源就是我自己，我并没有使用知乎那个本地运算的方法

**Comment by SerinaNya** [comment]
可，我的意思是如果你要转载巨佬的方法的话请注明。
看过你的代码，我知道你用的官方的 api
